version: "3.8"

services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-20
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/backend:cached
    working_dir: /workspace/backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
